In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies= movies.merge(credits, on="title")

In [7]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

In [8]:
movies = movies[['movie_id', 'title', 'genres', 'keywords', 'cast', 'crew']]

In [9]:
movies.head()

,movie_id,title,genres,keywords,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.duplicated().sum()

0

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
 import ast

In [14]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [15]:
movies['genres'] = movies['genres'].apply(convert)

In [16]:
movies['keywords'] = movies['keywords'].apply(convert)

In [17]:
def cast(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [18]:
movies['cast'] = movies['cast'].apply(cast)

In [19]:
movies.head()

,movie_id,title,genres,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
def crew(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [21]:
movies['crew'] = movies['crew'].apply(crew)

In [22]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ", "") for i in x])

In [23]:
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "") for i in x])

In [24]:
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [25]:
movies['tags'] = movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [26]:
new_df = movies[['movie_id', 'title', 'tags']]

In [27]:
new_df.head()
import nltk

In [28]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

<ipython-input-28-e498c0e361a2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [29]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [30]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [31]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-31-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [32]:
new_df['tags'][0]

'action adventur fantasi sciencefict cultur clash futur space war space coloni societi space travel futurist romanc space alien tribe alien planet cgi marin soldier battl love affair anti war power relat mind and soul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [33]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

<ipython-input-33-db70cfe1859e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [35]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [36]:
cv.get_feature_names()

['11',
 '15th',
 '16th',
 '17th',
 '18th',
 '1910',
 '1917',
 '1930',
 '1940',
 '1950',
 '1960',
 '1970',
 '1980',
 '1990',
 '1992',
 '1995',
 '19th',
 '2001',
 '21st',
 '3d',
 '50cent',
 '51',
 '60',
 '66',
 'aaliyah',
 'aamirkhan',
 'aaroneckhart',
 'aaronstanford',
 'aarontaylor',
 'abandon',
 'abbiecornish',
 'abduct',
 'abhishekbachchan',
 'abigailbreslin',
 'abil',
 'aborigin',
 'abram',
 'abroad',
 'absurd',
 'abus',
 'accent',
 'accid',
 'account',
 'accus',
 'acid',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'ad',
 'adambeach',
 'adambrodi',
 'adambrook',
 'adamcampbel',
 'adamcarolla',
 'adamdriv',
 'adamgarcia',
 'adamgoldberg',
 'adammckay',
 'adamrifkin',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adamtres',
 'adamwest',
 'adapt',
 'addict',
 'adolesc',
 'adolf',
 'adopt',
 'adrenalin',
 'adriangreni',
 'adrianlyn',
 'adrienbrodi',
 'adriennebarbeau',
 'adriánalonsobarona',
 'adult',
 'adulteri',
 'advanc',
 'adventur',
 'adversari',
 'advertis',
 'advic',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'age',
 'agenc',
 'agent',
 'aggress',
 'aid',
 'aidanquinn',
 'aimeegarcia',
 'air',
 'aircraft',
 'airplan',
 'airport',
 'akshaykumar',
 'al',
 'alanalda',
 'alanarkin',
 'alanj',
 'alanpark',
 'alanrickman',
 'alantaylor',
 'alantudyk',
 'alarm',
 'alaska',
 'albanian',
 'albertbrook',
 'albertfinney',
 'alberthugh',
 'alcatraz',
 'alcohol',
 'aldenehrenreich',
 'alecbaldwin',
 'alecguin',
 'alejandroamenábar',
 'alejandrogonzáleziñárritu',
 'alejandromonteverd',
 'alessandronivola',
 'alexand',
 'alexanderpayn',
 'alexanderskarsgård',
 'alexandradaddario',
 'alexandreaja',
 'alexapenavega',
 'alexisbledel',
 'alexkendrick',
 'alexpettyf',
 'alexproya',
 'alfonsocuarón',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'alicebraga',
 'aliceev',
 'aliciasilverston',
 'aliciavikand',
 'aliciawitt',
 'alien',
 'alilart',
 'alisonlohman',
 'aliv',
 'allegori',
 'alli',
 'allianc',
 'allig',
 'alon',
 'alp',
 'alpacino',
 'alter',
 'altern',
 'alysonhannigan',
 'alzheim',
 'alzheimer',
 'amandabyn',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amazon',
 'ambassador',
 'amberheard',
 'ambertamblyn',
 'ambigu',
 'ambit',
 'ambul',
 'ambush',
 'america',
 'americaferrera',
 'american',
 'amnesia',
 'amok',
 'amsterdam',
 'amus',
 'amyadam',
 'amyheckerl',
 'amypoehl',
 'amyryan',
 'amysmart',
 'anaclaudiatalancón',
 'anandtuck',
 'anarch',
 'ancient',
 'anderson',
 'andiemacdowel',
 'andrebraugh',
 'andrewadamson',
 'andrewbujalski',
 'andrewdavi',
 'andrewflem',
 'andrewgarfield',
 'andrewniccol',
 'andrewstanton',
 'android',
 'andrzejbartkowiak',
 'andyfickman',
 'andygarcía',
 'andylau',
 'andysamberg',
 'andyserki',
 'andytenn',
 'angel',
 'angelabassett',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'angst',
 'anim',
 'anjelicahuston',
 'annabel',
 'annabellasciorra',
 'annafari',
 'annafriel',
 'annakendrick',
 'annapaquin',
 'annasophiarobb',
 'annearch',
 'annebancroft',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anonym',
 'anoth',
 'ant',
 'antarct',
 'antarctica',
 'antholog',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthonyminghella',
 'anthonyquinn',
 'anthonyrusso',
 'anthropomorph',
 'anti',
 'antoinefuqua',
 'antoncorbijn',
 'antoniobandera',
 'antonyelchin',
 'apart',
 'apartheid',
 'ape',
 'apocalyps',
 'apocalypt',
 'apostl',
 'appl',
 'apprentic',
 'aquarium',
 'arab',
 'arabia',
 'arbitrari',
 'archaeologist',
 'archeolog',
 'archeologist',
 'archer',
 'archeri',
 'architect',
 'arci',
 'arctic',
 'area',
 'arena',
 'argument',
 'aristocrat',
 'arizona',
 'ark',
 'arm',
 'armandassant',
 'armi',
 'armiehamm',
 'arminmueller',
 'armor',
 'arnoldschwarzenegg',
 'arrang',
 'arrest',
 'arrog',
 'arrow',
 'arson',
 'art',
 'articl',
 'artifact',
 'artifici',
 'artist',
 'asabutterfield',
 'ash',
 'ashleyjudd',
 'ashleytisdal',
 'ashtonkutch',
 'asia',
 'asian',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atlant',
 'atom',
 'atomegoyan',
 'attack',
 'attempt',
 'attic',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audio',
 'audit',
 'audreyhepburn',
 'audreytaut',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'autism',
 'auto',
 'autobiograph',
 'automobil',
 'autoritian',
 'award',
 'awkward',
 'ax',
 'axe',
 'babi',
 'baby',
 'babysitt',
 'bachelor',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'ball',
 'ballet',
 'balloon',
 'baltasarkormákur',
 'baltimor',
 'bammargera',
 'band',
 'bangkok',
 'bank',
 'banker',
 'banner',
 'bar',
 'barbarahershey',
 'barbarian',
 'barbrastreisand',
 'barcelona',
 'barn',
 'barrier',
 'barrylevinson',
 'barrypepp',
 'barrysonnenfeld',
 'bartend',
 'base',
 'basebal',
 'basement',
 'basketbal',
 'bat',
 'bath',
 'bathroom',
 'bathtub',
 'batman',
 'battl',
 'battlefield',
 'bay',
 'bazluhrmann',
 'bdsm',
 'beach',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'beguil',
 'behead',
 'belgium',
 'bell',
 'belt',
 'benaffleck',
 'benbarn',
 'benchaplin',
 'benedictcumberbatch',
 'benfost',
 'bengazzara',
 'beniciodeltoro',
 'benito',
 'benjaminbratt',
 'benkingsley',
 'bennofürmann',
 'benstil',
 'benwhishaw',
 'berlin',
 'berniemac',
 'best',
 'bet',
 'betray',
 'bettemidl',
 'bettythoma',
 'beverli',
 'beyoncéknowl',
 'bia',
 'bibl',
 'biblic',
 'bicycl',
 'big',
 'biker',
 'bikini',
 'billard',
 'billbellami',
 'billcondon',
 'billewoodruff',
 'billhad',
 'billi',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyburk',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'billywild',
 'billyzan',
 'binocular',
 'biographi',
 'biolog',
 'bipolar',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bite',
 'bitten',
 'bittersweet',
 'black',
 'blackmail',
 'blackout',
 'blacksmith',
 'blade',
 'blairunderwood',
 'blakeedward',
 'blakel',
 'blame',
 'blast',
 'blaxploit',
 'blind',
 'blizzard',
 'block',
 'blog',
 'blond',
 'blood',
 'bloodi',
 'blow',
 'blue',
 'blueprint',
 'blunt',
 'blythedann',
 'boar',
 'board',
 'boat',
 'boazyakin',
 'bob',
 'bobbalaban',
 'bobbycoleman',
 'bobbyfarrelli',
 'bobclark',
 'bobfoss',
 'bobgunton',
 'bobhoskin',
 'bobodenkirk',
 'bobrafelson',
 'bobsaget',
 'bodi',
 'bodili',
 'body',
 'bodyguard',
 'bokeemwoodbin',
 'bollywood',
 'bomb',
 'bomber',
 'bon',
 'bonapart',
 'bond',
 'bondag',
 'bone',
 'bonfir',
 'bong',
 'bongjoon',
 'bonniehunt',
 'bono',
 'boobi',
 'book',
 'bookshop',
 'booth',
 'bootlegg',
 'border',
 'boredom',
 'bosnian',
 'boss',
 'boston',
 'botanist',
 'bottl',
 'bounti',
 'bourgeoisi',
 'bow',
 'bowl',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradanderson',
 'bradbird',
 'braddourif',
 'bradfurman',
 'bradleycoop',
 'bradpeyton',
 'bradpitt',
 'bradsilberl',
 'bradycorbet',
 'brain',
 'brainwash',
 'brandont',
 'braveri',
 'brawl',
 'brazil',
 'brazilian',
 'break',
 'breakdanc',
 'breakdown',
 'breast',
 'breckeisn',
 'breckinmey',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brentonthwait',
 'brentspin',
 'brettleonard',
 'brettratn',
 'brianaevigan',
 'briancox',
 'briandennehi',
 'briandepalma',
 'briangibson',
 'brianhelgeland',
 'brianherzling',
 'briankoppelman',
 'brianlev',
 'briannesiddal',
 'briano',
 'brianrobbin',
 'briantaylor',
 'briantrenchard',
 'brianvanholt',
 'brick',
 'bride',
 'bridegroom',
 'bridesmaid',
 'bridg',
 'bridgetfonda',
 'bridgetmoynahan',
 'bridgettewilson',
 'brief',
 'briefcas',
 'brielarson',
 'brien',
 'brighton',
 'britain',
 'british',
 'britmarl',
 'brittanymurphi',
 'brittanysnow',
 'brittrobertson',
 'broadcast',
 'broadway',
 'broken',
 'broker',
 'bronx',
 'brood',
 'brook',
 'brookeadam',
 'brookeshield',
 'brooklyn',
 'broom',
 'broth',
 'brothel',
 'brother',
 'brown',
 'bruce',
 'bruceberesford',
 'brucecampbel',
 'brucedavison',
 'brucedern',
 'brucegreenwood',
 'brucemcculloch',
 'brucepayn',
 'brucesp',
 'brucewilli',
 'bruge',
 'brumbi',
 'brutal',
 'bryancranston',
 'bryansing',
 'brycedallashoward',
 'bu',
 'budapest',
 'buddhism',
 'buddhist',
 'buddi',
 'budget',
 'buffalo',
 'build',
 'bull',
 'bullet',
 'bulli',
 'bum',
 'bungee',
 'bunker',
 'bunni',
 'bureaucraci',
 'burglar',
 'burglari',
 'buri',
 'burial',
 'burn',
 'burrsteer',
 'burtlancast',
 'burtreynold',
 'bush',
 'busi',
 'butler',
 'bythewood',
 'cabin',
 'caesar',
 'cafe',
 'cage',
 'cairo',
 'california',
 'callboy',
 'calliekhouri',
 'callumblu',
 'calypso',
 'camaraderi',
 'cambodia',
 'camcord',
 'camelot',
 'cameo',
 'camera',
 'cameronbright',
 'cameroncrow',
 'camerondiaz',
 'cameronrichardson',
 'camgigandet',
 'camillabel',
 'camilledelamarr',
 'camp',
 'campaign',
 'campbellscott',
 'campfir',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'candl',
 'candlelight',
 'cane',
 'cannabi',
 'cannib',
 'cano',
 'canuxploit',
 'canyon',
 'cap',
 'caper',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'card',
 'care',
 'career',
 'caretak',
 'careymulligan',
 'cargo',
 'caribbean',
 'caricevanhouten',
 'carjack',
 'carlagugino',
 'carlfranklin',
 'carlo',
 'carlossaldanha',
 'carlyschroed',
 'carmenejogo',
 'carniv',
 'carol',
 'carolina',
 'carpet',
 'carriag',
 'carrie',
 'carriefish',
 'carrier',
 'cartel',
 'cartoon',
 'caruso',
 'caryelw',
 'case',
 'caseyaffleck',
 'casino',
 'cast',
 'castl',
 'castrat',
 'casual',
 'cat',
 'cataclysm',
 'catastroph',
 'cateblanchett',
 'catherinedeneuv',
 'catherinehardwick',
 'catherinekeen',
 'catherinemccormack',
 'catherineo',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'cavalri',
 'cave',
 'cavemen',
 'cedrictheentertain',
 'celebr',
 'cell',
 'cello',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'ceremoni',
 'cgi',
 'chadmichaelmurray',
 'chain',
 'chainsaw',
 'chair',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chandor',
 'chang',
 'channingtatum',
 'chao',
 'chapel',
 'charact',
 'chariti',
 'charl',
 'charlesd',
 'charlesferguson',
 'charlesherman',
 'charlesmartinsmith',
 'charless',
 'charliecox',
 'charlieday',
 'charliehunnam',
 'charliesheen',
 'charlietahan',
 'charlizetheron',
 'charlotterampl',
 'charltonheston',
 'chase',
 'chat',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chimcbrid',
 'chimp',
 'chimpanze',
 'china',
 'chines',
 'chipmunk',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choimin',
 'choir',
 'cholo',
 'choru',
 'chosen',
 'chowyun',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chriskattan',
 'chrisklein',
 'chrismil',
 'chrisnoth',
 'chriso',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'chrissand',
 'christ',
 'christian',
 'christianbal',
 'christianclavi',
 'christianslat',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christophereccleston',
 'christopherguest',
 'christopherlambert',
 'christopherlloyd',
 'christophermcdonald',
 'christophermcquarri',
 'christophermintz',
 'christophernolan',
 'christopherplumm',
 'christopherreev',
 'christopherwalken',
 'christophwaltz',
 'christuck',
 'chriswedg',
 'chrisweitz',
 'chu',
 'chuckrussel',
 'church',
 'cia',
 'ciaránhind',
 'cigar',
 'cigarett',
 'cillianmurphi',
 'cinderella',
 'cinema',
 'cinemat',
 'circu',
 'citi',
 'civil',
 'clairedan',
 'claireforlani',
 'clan',
 'clancybrown',
 'clarkgabl',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'clau',
 'claudevandamm',
 'claustrophobia',
 'cleaduval',
 'clerk',
 'cliff',
 'cliffcurti',
 'climat',
 'climb',
 'clinic',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'closet',
 'clown',
 'club',
 'clumsi',
 'coach',
 'coal',
 'coast',
 'coaster',
 'cocain',
 'cockney',
 'cockroach',
 'cocktail',
 'code',
 'coffe',
 'coffin',
 'cohabit',
 'cohen',
 'coin',
 'cold',
 'colehaus',
 'colinfarrel',
 'colinfirth',
 'collar',
 'collect',
 'collector',
 'colleg',
 'collis',
 'colmfeor',
 'colmmeaney',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'columbia',
 'coma',
 'comb',
 'combat',
 'come',
 'comeback',
 'comedi',
 'comedian',
 'comet',
 'comic',
 'command',
 'commando',
 'commentari',
 'commerci',
 'commit',
 'common',
 'commun',
 'compani',
 'compass',
 'competit',
 'compos',
 'compuls',
 'comput',
 'concentr',
 'concert',
 'concili',
 'condom',
 'confeder',
 'confer',
 'confess',
 'confid',
 'confilct',
 'conflict',
 'congress',
 'connel',
 'connienielsen',
 'connor',
 'conradvernon',
 'conscienc',
 'conserv',
 'conspiraci',
 'construct',
 'contact',
 'contest',
 'contract',
 'control',
 'conveni',
 'convent',
 'convers',
 'convert',
 'convict',
 'convoy',
 'cook',
 'cop',
 'corbinbernsen',
 'cord',
 'coreyfeldman',
 'coron',
 'corp',
 'corpor',
 'corps',
 'correspond',
 'corrupt',
 'cosmato',
 'costasmandylor',
 ...]

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
similarity = cosine_similarity(vectors)

In [48]:
similarity[1]

array([0.0993808 , 1.        , 0.08164966, ..., 0.05270463, 0.        ,
       0.        ])

In [53]:
def recommend(movie):
    movie_index = new_df[new_df['title']==movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [55]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
The Rise of the Krays
Batman & Robin
Ajami

In [56]:
import pickle

In [57]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [58]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))